name: Automated Content Poster

on:
  schedule:
    # Runs every day at 9 AM UTC.
    # Use a cron calculator like https://crontab.guru/ to customize.
    - cron: '0 9 * * *'
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab on GitHub.

jobs:
  check-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install firefox
          playwright install-deps firefox

      - name: Run the LinkedIn Playwright automation
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
          POST_SLOT: ${{ secrets.POST_SLOT }}
          DISPLAY: ':99'
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 3
          python linkedin_playwright.py 